---
# Git configuration
git_user_name: "Your Name"
git_user_email: "your.email@example.com"

# GitHub configuration
github_username: "your_github_username"
github_email: "your.github@email.com"

# Applications that need manual installation or special handling
manual_applications:
  - name: "DaVinci Resolve"
    url: "https://www.blackmagicdesign.com/products/davinciresolve/"
  - name: "Microsoft Office"
    url: "https://www.office.com/"
  - name: "Fusion 360"
    url: "https://www.autodesk.com/products/fusion-360/overview"

# Oh My Zsh configuration
zsh_theme: "powerlevel10k/powerlevel10k"

# Additional configurations
configure_ohmyzsh: true